language: python

services:
  - docker

install:
  - echo docker pull byjg/k8s-ci

script:
  - echo docker run --privileged -v  /tmp/z:/var/lib/containers -it --rm -v $PWD:/work -w /work -e DOCKER_USERNAME=$DOCKER_USERNAME -e DOCKER_PASSWORD=$DOCKER_PASSWORD -e DOCKER_REGISTRY=$DOCKER_REGISTRY byjg/k8s-ci /work/build-multiarch.sh

jobs:
  include:
    - stage: documentation
      if: (branch = master) AND (NOT (type IN (pull_request)))
      install: skip
      script: "curl https://opensource.byjg.com/add-doc.sh | bash /dev/stdin devops docker-static-httpserver"