apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "static-httpserver.fullname" . }}
  labels:
    {{- include "static-httpserver.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "static-httpserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "static-httpserver.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- if .Values.parameters.htmlTitle }}
            - name: HTML_TITLE
              value: {{ .Values.parameters.htmlTitle }}
            {{- end }}
            {{- if .Values.parameters.title }}
            - name: TITLE
              value: {{ .Values.parameters.title }}
            {{- end }}
            {{- if .Values.parameters.message }}
            - name: MESSAGE
              value: {{ .Values.parameters.message }}
            {{- end }}
            {{- if .Values.parameters.backgroundImage }}
            - name: BG_IMAGE
              value: {{ .Values.parameters.backgroundImage }}
            {{- end }}
            {{- if .Values.parameters.facebook }}
            - name: FACEBOOK
              value: {{ .Values.parameters.facebook }}
            {{- end }}
            {{- if .Values.parameters.twitter }}
            - name: TWITTER
              value: {{ .Values.parameters.twitter }}
            {{- end }}
            {{- if .Values.parameters.youtube }}
            - name: YOUTUBE
              value: {{ .Values.parameters.youtube }}
            {{- end }}
            {{- if .Values.parameters.spaMode }}
            - name: SPA_MODE
              value: {{ .Values.parameters.spaMode | quote }}
            {{- end }}
            {{- if .Values.parameters.port }}
            - name: PORT
              value: {{ .Values.parameters.port | quote }}
            {{- end }}
            {{- if .Values.parameters.tlsPort }}
            - name: TLS_PORT
              value: {{ .Values.parameters.tlsPort | quote }}
            {{- end }}
            {{- if .Values.parameters.tlsCertDir }}
            - name: TLS_CERT_DIR
              value: {{ .Values.parameters.tlsCertDir | quote }}
            {{- end }}
            {{- if .Values.parameters.cacheMaxSize }}
            - name: CACHE_MAX_SIZE
              value: {{ .Values.parameters.cacheMaxSize | quote }}
            {{- end }}
            {{- if .Values.parameters.cacheMaxFileSize }}
            - name: CACHE_MAX_FILE_SIZE
              value: {{ .Values.parameters.cacheMaxFileSize | quote }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
